### ISSUE TITLE
The theme is not taking effect. Do you know why?

### ISSUE THREAD

**Issue by jiaxiangwang** [intansemc2/test-monaco-languageclient#1]
The theme is not taking effect. Do you know why?

**Comment by intansemc2** [comment]
### i've find out how to get the theme and syntax highlight to work:

Here is the step by step:

- Step 1: Add the `importMetaUrlPlugin`:

Install the `@codingame/esbuild-import-meta-url-plugin` via `pnpm`

Add it to the vite.config.ts file

```
import importMetaUrlPlugin from '@codingame/esbuild-import-meta-url-plugin';
```

Add the `optimizeDeps` to the vite config:

```
optimizeDeps: {
    esbuildOptions: {
        plugins: [importMetaUrlPlugin]
    }
}
```

+ Step 2: Add the `monaco-vscode-python-default-extension` to the `+page.svelte` file to get syntax highlight

```
import '@codingame/monaco-vscode-python-default-extension';
```

+ Step 3: To init a new theme, add these lines of code to the `main.ts` file to init a new theme:

```
wrapper.getMonacoEditorApp()?.updateUserConfiguration(
    JSON.stringify({
        'editor.wordWrap': 'on',
        'editor.fontSize': 18,
        'editor.tabWidth': 4,
        'editor.singleQuote': true,
        'editor.fontFamily': "'Fira Code', 'monospace', monospace",
        'editor.fontLigatures': true,
        'editor.stickyScroll.scrollWithEditor': false,
        'workbench.tree.enableStickyScroll': false,
        'editor.stickyScroll.enabled': false,
        'workbench.colorTheme': MONACO_SUPPORT_THEME.dark
    })
);
```

the support theme i've find out is:

```
enum MONACO_SUPPORT_THEME {
	dark = 'Default Dark Modern',
	light = 'Default Light Modern',
	high_contrast_dark = 'Default High Contrast',
	high_contrast_light = 'Default High Contrast Light',
	dark_plus = 'Default Dark+',
	light_plus = 'Default Light+'
}
```

**Comment by intansemc2** [comment]
![test](https://github.com/user-attachments/assets/db19b63e-ab44-490c-b6e3-4b5a83afb522)

I've updated the code to include the changes I mentioned, make theme and syntax highlight working.
